Урок-03: Однофайловые компоненты (SFC)
js-tasks-ru/vue-20231109_gsy pull request #4
Opened 2023-11-16 12:10 UTC by GoncharSY

- Обе задачи решил;
- Авто-тесты проходит;
- Визуально тоже нормально.

В этот раз я сомневаюсь, правильно ли я все понял - надеюсь, что так. Если что, дождусь вебинара, и после просмотра вернусь, чтобы пере/до-делать.

2023-11-16 12:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-16 19:10 UTC, ShGKme requested changes
Стили в `03-sfc/02-UiTransitionGroupFade` получились стишком глубокими. К сожалению, идеальной инкапсуляции из-за бага в Vue тут не добиться. Но требуется хотя бы действовать только на элементы внутри этого компонента.

2023-11-16 19:10 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +:deep(.fade-list-move) {
Такое использование `:deep` фактически полностью убирает инкапсуляцию стилей, будто `scoped` и не было. В итоге стили действуют на все анимации с `fade-list` на странице (даже если они другой реализации).

2023-11-16 19:10 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
>  }
А этот стиль буквально означает, что он действует вообще на все элементы на странице.

2023-11-18 06:37 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-18 06:44 UTC, GoncharSY commented
Еще почитал материалы на тему стилей, посмотрел, что происходит в результирующем коде через DevTools. Кажется понял, в чем была проблема. Думаю теперь стало по-лучше...

![image](https://github.com/js-tasks-ru/vue-20231109_gsy/assets/47101945/33d16b8e-d97d-4596-bd57-2fc61731f910)

2023-11-18 06:46 UTC, ShGKme commented
Принято 👍

2023-11-22 17:16 UTC, GoncharSY commented
Можете тогда одобрить слияние PR с основной веткой?

2023-11-22 17:32 UTC, ShGKme approved these changes

2023-11-22 17:32 UTC, ShGKme commented
> Можете тогда одобрить слияние PR с основной веткой?

Сорри, сообщение случайно отправилось как комментарий, а не как ревью...

2023-11-22 17:32 UTC, merged