Урок-04: Консольные утилиты (Vue CLI)
js-tasks-ru/vue-20231109_gsy pull request #5
Opened 2023-11-22 17:00 UTC by GoncharSY

- Все четыре задачи решены;
- Авто-тесты проходит;
- Визуально похоже на примеры, что в условиях задач.

Четвертая задача, с календарем, понравилась. Почти весь день над ней сидел, решал. Этим вечером календарь работает - моральное удовлетворение получено, и настроение хорошее.

2023-11-22 17:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-22 17:40 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-24 23:53 UTC, ShGKme requested changes

2023-11-24 23:53 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToast.vue
> +  name: 'TheToast',
Имена с префиксом `The` обычно используют для компонентов, которые выводятся на странице один раз. Артикул `The` в англ. показывает, что это "конкретный" компонент, что у него будет "один конкретный экземпляр".

2023-11-24 23:53 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
`opened` - собственное состояние компонента. Компонент сам определяет, когда он открыт, а когда закрыт.

Но `iconed` и `option` - не собственное состояние. Эти свойства хранят только результат вычисления от входных параметров. `iconed` явно результат вычисления от `options`. `option` - от `options` + `modelValue`. Сейчас это реализовано вручную, с отслеживанием, но лучше это явно описать именно как вычисляемое свойство.

2023-11-24 23:53 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +        if (!nv) this.option = null;
`modelValue` может быть `falsy`, но это не значит, что никакой вариант не выбран. Значение какого-то варианта вполне может быть, например, пустой строкой.

2023-11-24 23:53 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +          if (!this.option) throw new Error('unknown option');
Если передали `modelValue`, для которого нет `option` - это лишь означает, что никакой вариант из представленных не выбран. Лучше не выбрасывать в таких случаях исключения.

2023-11-24 23:53 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      },
Этот метод мутирует результат вычисления вычисляемого свойства. Ни в коем случае нельзя мутировать вычисляемые свойства, они только для чтения. В `cells` всегда должен быть именно результат функции его вычисления. В любой момент времени Vue может перевычислить значение вычисляемого свойства. (И он может это делать, ведь вычисление не должно никак влиять на значение в том же состоянии).

2023-11-25 09:34 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-25 09:35 UTC, GoncharSY commented on 04-vue-cli/02-TheToaster/components/TheToast.vue
> +  name: 'TheToast',
Переименовал компонент в `UiToast`.

2023-11-25 09:39 UTC, GoncharSY commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Переделал,  и количество кода сократилось. Сейчас это стало очевидным, но когда первый раз решал, почему-то сделал через `watch`. Наверное, взгляд замылился просто.

2023-11-25 09:40 UTC, GoncharSY commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +        if (!nv) this.option = null;
Исправил.

2023-11-25 09:41 UTC, GoncharSY commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +          if (!this.option) throw new Error('unknown option');
Исправил. На момент решения, подумалось, что так было бы правильней.

2023-11-25 09:47 UTC, GoncharSY commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      },
Переделал алгоритм распределения митапов по дням в календаре. Убрал метод `distributeEvents`, и теперь массив с митапами за месяц передаю в компоненты ячеек (`CalendarCell`). Внутри ячеек фильтрую митапы для одного дня. Пока что ничего лучше не придумал... Если есть более правильный способ, дайте подсказку, пожалуйста.

2023-11-25 11:23 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      },
Можно один раз пробежаться по данным, чтобы собрать более удобную структуру получения данных по дате. Например, собрать объект, где ключ — дата, а значение — массив данных для этой даты. Тогда можно будет сразу выводить данные для конкретного дня, не перебирая снова и снова циклами одни и те же данные для поиска данных текущего дня.

2023-11-25 11:24 UTC, ShGKme approved these changes
Все задачи приняты 🔥

2023-11-25 11:25 UTC, merged